"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LensHub__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LensHub__factory_1 = require("./LensHub__factory");
Object.defineProperty(exports, "LensHub__factory", { enumerable: true, get: function () { return LensHub__factory_1.LensHub__factory; } });
